-- MySQL Script generated by MySQL Workbench
-- Fri Feb 10 10:51:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biometria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biometria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biometria` DEFAULT CHARACTER SET utf8 ;
USE `biometria` ;

-- -----------------------------------------------------
-- Table `biometria`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biometria`.`area` (
  `idarea` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idarea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biometria`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biometria`.`cargo` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `area_idarea` INT NOT NULL,
  PRIMARY KEY (`idcargo`, `area_idarea`),
  INDEX `fk_cargo_area_idx` (`area_idarea` ASC) VISIBLE,
  CONSTRAINT `fk_cargo_area`
    FOREIGN KEY (`area_idarea`)
    REFERENCES `biometria`.`area` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biometria`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biometria`.`persona` (
  `documento` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `apellidos` VARCHAR(200) NOT NULL,
  `huella1` BLOB NULL,
  `huella2` BLOB NULL,
  `foto` VARCHAR(200) NULL,
  `activo` VARCHAR(5) NULL,
  `fecha_creacion` DATE NULL,
  `hora_creacion` VARCHAR(45) NULL,
  `username` VARCHAR(200) NULL,
  `password` VARCHAR(200) NULL,
  `cargo_idcargo` INT NOT NULL,
  `cargo_area_idarea` INT NOT NULL,
  `user_created` INT NULL,
  `user_update` INT NULL,
  `fecha_update` DATE NULL,
  `hora_update` VARCHAR(45) NULL,
  PRIMARY KEY (`documento`, `cargo_idcargo`, `cargo_area_idarea`),
  INDEX `fk_persona_cargo1_idx` (`cargo_idcargo` ASC, `cargo_area_idarea` ASC) VISIBLE,
  CONSTRAINT `fk_persona_cargo1`
    FOREIGN KEY (`cargo_idcargo` , `cargo_area_idarea`)
    REFERENCES `biometria`.`cargo` (`idcargo` , `area_idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biometria`.`tipo_visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biometria`.`tipo_visita` (
  `idtipo_visita` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idtipo_visita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biometria`.`visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biometria`.`visita` (
  `idvisita` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  `tipo_visita_idtipo_visita` INT NOT NULL,
  `persona_documento` VARCHAR(45) NOT NULL,
  `mac` VARCHAR(200) NULL,
  `ip` VARCHAR(45) NULL,
  `codigo_pdv` INT NULL,
  `nombre_pdv` VARCHAR(200) NULL,
  PRIMARY KEY (`idvisita`, `tipo_visita_idtipo_visita`, `persona_documento`),
  INDEX `fk_visita_tipo_visita1_idx` (`tipo_visita_idtipo_visita` ASC) VISIBLE,
  INDEX `fk_visita_persona1_idx` (`persona_documento` ASC) VISIBLE,
  CONSTRAINT `fk_visita_tipo_visita1`
    FOREIGN KEY (`tipo_visita_idtipo_visita`)
    REFERENCES `biometria`.`tipo_visita` (`idtipo_visita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visita_persona1`
    FOREIGN KEY (`persona_documento`)
    REFERENCES `biometria`.`persona` (`documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
